### ISSUE TITLE
Support for get over SSH

### ISSUE THREAD

**Issue by palsivertsen** [instrumentisto/glide-docker-image#1]
Sometimes dependencies, like private repos, requires a SSH to get libraries:
```
- package: github.com/example/private
  repo: git@github.com/example/private.git
```
Add a SSH client to image should solve this.
```
apk add openssh
```

**Comment by tyranron** [comment]
@palsivertsen nice catch!

Wanna made a PR?

**Comment by palsivertsen** [comment]
Thanks!
Which Docker tag(s) includes these changes? `0.13`XX?

**Comment by tyranron** [comment]
@palsivertsen `0.13.0-go1.9`, `0.13.0`, `0.13`, `latest`
