### ISSUE TITLE
resulting vendor file is owned by root

### ISSUE THREAD

**Issue by arrivets** [instrumentisto/glide-docker-image#2]
Hey,

When I run the command `docker run --rm -it -v $(pwd):/go/src/my/pkg/name -w /go/src/my/pkg/name instrumentisto/glide install`, the vendor file is create on locally but it is owned by root.
I have tried changing the user inside the container with -u `id -u $USER` but then I get permission issues inside the container.

I would like the the vendor folder to be owned by the current user

Any ideas?
thanks

**Comment by tyranron** [comment]
@arrivets I see no comfortable way to do what your want. Your current user is not present inside container environment, so you can't act from his name.

You may try to use `nobody` user, but this does not change things either. You still need to change owner after.

You may use following `Makefile` to solve your problem:
```makefile
cmd ?= install

deps.glide:
	docker run --rm -v "$(PWD)":/go/src/$(PROJ_NAME) -w /go/src/$(PROJ_NAME) \
		instrumentisto/glide $(cmd)
	chown -R $(shell whoami) vendor/
```

And make stuff in single command like `make deps.glide`.

**Comment by arrivets** [comment]
Thanks. That makes sense. I'll do something along these lines.

**Comment by tyranron** [comment]
@arrivets btw, why do you need that?

Files are created with `0644` rights and folders with `0755` rights. So you may read them by any user. Any changes to `vendor/` dir are supposed to be done via `docker run` (if you're using this image), which uses `root` for modification. So I can't imagine normal scenario where you're running in files permissions troubles.

**Comment by arrivets** [comment]
You are right, I don't really need it. I just didn't have permission to delete the folder.
It just seems nicer that the output of a command is owned by the user who ran the command.
But again, it is not a big deal. I was using this as part of a circleci automated build but I ended up creating another image based on circleci/golang:
```
FROM circleci/golang:1.9.2-stretch
RUN curl https://glide.sh/get | sh
```
